workflows:
  android-apk-workflow:
    name: Build Android APK
    instance_type: mac_mini_m1
    scripts:
      - name: Build Debug APK
        script: | 
          # Move into the folder where your gradlew file actually is
          cd HERE 
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
